language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php tests/
