language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - phpenv config-rm xdebug.ini
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpcs --ignore=vendor/* --extensions=php ./ --standard=PSR2
  - ./vendor/bin/phpunit --bootstrap ./vendor/autoload.php tests/
